train:
  id: csgo
  size: [150, 280]
num_actions: 51
path_data_low_res: /home/kangrui/projects/world_model/diamond/data_processed/low_res # TO DEFINE
path_data_full_res: /home/kangrui/projects/world_model/diamond/data_processed/full_res # TO DEFINE
keymap: csgo
